### ISSUE TITLE
`this` is not set correctly in event callbacks

### ISSUE THREAD

**Issue by jens1101** [Yankovsky/nouislider-angular#18]
From the [documentation](https://refreshless.com/nouislider/events-callbacks/#section-binding):

> For all events, this is set to the current slider's public API, containing (among others) the 'get' and 'set' methods.

However, this is not true when I use your directive event binding.
Example:

``` javascript
$scope.eventHandlers = {
    end: function (args) {
        console.log(args, this); //Logs event arguments and 'Window' object
    }
}
```

**Comment by jens1101** [comment]
I fixed it myself, because I needed this fix ASAP. The code I used is:

``` javascript
angular.forEach(noUiSliderEvents, function (handler, event) {
    noUiSliderInstance.on(event + '.noUiSlider', function () {
        var handlerArguments = Array.prototype.slice.call(arguments);
        var self = this;
        $scope.$applyAsync(function () {
            handler.apply(self, handlerArguments);
        });
    });
});
```

This is in the `createSlider` function.

Sorry, I know the proper way to do this is via a pull request, but I was lazy.

**Comment by Yankovsky** [comment]
@jens1101 can you make a pull request with these changes?

**Comment by jens1101** [comment]
@Yankovsky I created a pull request. I also created minified code.

**Comment by Yankovsky** [comment]
@jens1101 Thank you very much! I updated plugin version, now it is 2.6.0

**Comment by zatchgordon** [comment]
Using the following event handler, "this" is undefined:

```
            vm.sliderEvents = {
                change: function (values, handle, unencoded) {
                    console.log("this", this)
                    console.log("values", values);
                    console.log("handle", handle);
                    console.log("unencoded", unencoded);
                }
            }
```
Tried version 2.6.2
Downgraded to 2.6.0 -- still doesn't work for me
nouislider is 8.3.0
